### ISSUE TITLE
Logovanje primljenog i poslatog JSON-a radi debugovanja

### ISSUE THREAD

**Issue by Shinhan** [nebkam/netsuite-restlet-php-sdk#11]
Monolog ili nešto drugo, na način tako da svaki korisnik ove biblioteke može na svoj način da loguje u fajlove, Mongo, MySQL ili nešto drugo.

**Comment by nebkam** [comment]
Dodat drugi, opcionalni, parametar za `ApiService` koji implementira PSR3 `LoggerInterface` i prosleđuje ga u Guzzle putem middleware, tako da beleži sve request i reponse podatke.
Monolog korisnici mogu konfigurisati koje god handlere žele i proslediti logger (u Symfony je to jedan "kanal", jedna kombinacija handlera) biblioteci.
- `v1` https://github.com/nebkam/netsuite-restlet-php-sdk/releases/tag/1.3.1
- `v2` https://github.com/nebkam/netsuite-restlet-php-sdk/releases/tag/2.4.1
