### ISSUE TITLE
Anonimizacija podataka u tests folderu

### ISSUE THREAD

**Issue by silvesterk** [nebkam/netsuite-restlet-php-sdk#13]
Trenutno bilo ko moze da procita podatke o tome koje departmane imamo, ko su nam zaposleni i slično smatram da je to potrebno anonimizovati.

**Comment by nebkam** [comment]
Misliš iz koda ili..?
Za pozivanje API servisa je potrebna autorizacija

**Comment by silvesterk** [comment]
U /tests folderu json fajlovi koji sluze za testiranje sadrze licne podatke.
