### ISSUE TITLE
Guzzle method Utils::chooseHandler does not exist in versions lower than 7

### ISSUE THREAD

**Issue by silvesterk** [nebkam/netsuite-restlet-php-sdk#25]
**File**: src/ApiClient.php

```php
private function bootstrapGuzzle(?LoggerInterface $logger): Client
		{
		$stack = new HandlerStack();
                // The line with the method
		$stack->setHandler(Utils::chooseHandler());
		if ($logger)
			{
			$stack->push(Middleware::log($logger, new MessageFormatter(MessageFormatter::DEBUG), LogLevel::DEBUG));
			}

		return new Client([
			'handler' => $stack
		]);
		}
```
**Error message**: Call to undefined method GuzzleHttp\Utils::chooseHandler()
**Guzzle version**: ^6.3

Changing the Guzzle version is not a possibility .

I quickfixed the issue on my local by changing the line in question with the following code:
```php
$stack->setHandler(new CurlHandler());
```

**Comment by nebkam** [comment]
Deployed in release [`2.5.0`](https://github.com/nebkam/netsuite-restlet-php-sdk/releases/tag/2.5.0)
