### ISSUE TITLE
ApiServicetest::testGetItems fails in production

### ISSUE THREAD

**Issue by nebkam** [nebkam/netsuite-restlet-php-sdk#39]
Allegedly, fail is because of the field `custitem_item_old_erp_id` in the suiteQL query, which field doesn't exist in the production environment.
I've assigned @silvesterk because he implemented the method

**Comment by nebkam** [comment]
Removing that field from the query does make the test pass

**Comment by nebkam** [comment]
@silvesterk  and anyone else of interest - is it OK to remove that field from the query (and it won't be in the response)?

**Comment by silvesterk** [comment]
No, we do need a link between the old id and the id in NetSuite.

**Comment by silvesterk** [comment]
It would be ok if they initially open up this field but remove it afterward (after we synced all of the existing items).

**Comment by silvesterk** [comment]
The issue is that the field has been renamed from: custitem_item_old_erp_id (sandbox) to oldErpId (production)
